fix: make test-frontend doesn't locally for all
Running make test or make test-frontend spit this out for me locally. Torching node_modules didn't seem to help.

robin@robins-MacBook-Pro ~/Dev/code/sandwich % yarn test:unit

 RUN  v4.0.4 /Users/robin/Dev/code/sandwich

...

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

...

TypeError: Cannot read properties of undefined (reading 'get')
 ❯ Object.<anonymous> node_modules/webidl-conversions/lib/index.js:325:94
 ❯ Module._compile node:internal/modules/cjs/loader:1364:14
 ❯ Object.Module._extensions..js node:internal/modules/cjs/loader:1422:10
 ❯ Module.load node:internal/modules/cjs/loader:1203:32
 ❯ Function.Module._load node:internal/modules/cjs/loader:1019:12
 ❯ Module.require node:internal/modules/cjs/loader:1231:19
 ❯ require node:internal/modules/helpers:177:18
 ❯ Object.<anonymous> node_modules/whatwg-url/lib/URL.js:3:21
 ❯ Module._compile node:internal/modules/cjs/loader:1364:14
 ❯ Object.Module._extensions..js node:internal/modules/cjs/loader:1422:10

...

 Test Files  no tests
      Tests  no tests
     Errors  1 error
   Start at  15:16:48
   Duration  215ms (transform 0ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 0ms)

switching to happy-dom seems to work, lets see if it runs in CI

https://new-hippo.atlassian.net/browse/HC-75